agg_index: 2
havlval: sum
havop: '>'
havrval: '1000'
joinconfig:
  join_col_index: 0
  table1: zipcodes
  table1_len: 4
  table2: users
  table2_len: 5
  wherelval: 1
  whereop: <
  whererval: '49'
  wheretable: 2
pathconfig:
  hadoop_streaming_jar: /usr/share/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.2.0.jar
  input: test
  outputdir: op
  parentdir: test
sel_col_indexes:
- 1
