agg_index: 2
havlval: sum
havop: '>'
havrval: '1000'
joinconfig:
  join_col_index: 4
  table1: users
  table2: zipcodes
  wherelval: 0
  whereop: '='
  whererval: '23322'
  wheretable: 2
pathconfig:
  hadoop_streaming_jar: /usr/share/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.2.0.jar
  input: test
  outputdir: op
  parentdir: test
sel_col_indexes:
- 1
